# Generated by Django 5.2.1 on 2025-05-08 19:54

import Store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Store.models.product_image_path),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_time_of_order',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
